version: "3"
services:
    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        container_name: zookeeper
        ports:
            - 2181:2181
    kafka:
        image: wurstmeister/kafka:2.11-1.1.0
        container_name: kafka
        depends_on:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_CREATE_TOPICS: topic-1:1:1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        ports:
            - 9092:9092
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    producer:
        build: ./producer
        container_name: producer
        command: sh -c "dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9092 npm start"
        depends_on:
            - zookeeper
            - kafka
        environment:
            PRODUCER_PORT: 8080
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        ports:
            - 8080:8080
